# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xilinx/projects/example_project/example_project.srcs/sources_1/bd/zybo_example/ip/zybo_example_proc_sys_reset_0_0/zybo_example_proc_sys_reset_0_0.xci
# IP: The module: 'zybo_example_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx/projects/example_project/example_project.gen/sources_1/bd/zybo_example/ip/zybo_example_proc_sys_reset_0_0/zybo_example_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_example_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/xilinx/projects/example_project/example_project.gen/sources_1/bd/zybo_example/ip/zybo_example_proc_sys_reset_0_0/zybo_example_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_example_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/xilinx/projects/example_project/example_project.srcs/sources_1/bd/zybo_example/ip/zybo_example_proc_sys_reset_0_0/zybo_example_proc_sys_reset_0_0.xci
# IP: The module: 'zybo_example_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx/projects/example_project/example_project.gen/sources_1/bd/zybo_example/ip/zybo_example_proc_sys_reset_0_0/zybo_example_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_example_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/xilinx/projects/example_project/example_project.gen/sources_1/bd/zybo_example/ip/zybo_example_proc_sys_reset_0_0/zybo_example_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_example_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
