# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zybo_example/zybo_example.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_example || ORIG_REF_NAME==zybo_example} -quiet] -quiet

# IP: bd/zybo_example/ip/zybo_example_processing_system7_0_0/zybo_example_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_example_processing_system7_0_0 || ORIG_REF_NAME==zybo_example_processing_system7_0_0} -quiet] -quiet

# IP: bd/zybo_example/ip/zybo_example_proc_sys_reset_0_0/zybo_example_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_example_proc_sys_reset_0_0 || ORIG_REF_NAME==zybo_example_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zybo_example/ip/zybo_example_axi_interconnect_0_imp_xbar_0/zybo_example_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_example_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==zybo_example_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/zybo_example/ip/zybo_example_axi_interconnect_0_imp_auto_pc_1/zybo_example_axi_interconnect_0_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_example_axi_interconnect_0_imp_auto_pc_1 || ORIG_REF_NAME==zybo_example_axi_interconnect_0_imp_auto_pc_1} -quiet] -quiet

# IP: bd/zybo_example/ip/zybo_example_axi_interconnect_0_imp_auto_pc_0/zybo_example_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_example_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==zybo_example_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/zybo_example/ip/zybo_example_axi_interconnect_0_0/zybo_example_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_example_axi_interconnect_0_0 || ORIG_REF_NAME==zybo_example_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/zybo_example/ip/zybo_example_axi_gpio_0_0/zybo_example_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_example_axi_gpio_0_0 || ORIG_REF_NAME==zybo_example_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zybo_example/ip/zybo_example_axi_bram_ctrl_0_0/zybo_example_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_example_axi_bram_ctrl_0_0 || ORIG_REF_NAME==zybo_example_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/zybo_example/ip/zybo_example_blk_mem_gen_0_0/zybo_example_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_example_blk_mem_gen_0_0 || ORIG_REF_NAME==zybo_example_blk_mem_gen_0_0} -quiet] -quiet

# XDC: d:/xilinx/projects/example_project/example_project.gen/sources_1/bd/zybo_example/zybo_example_ooc.xdc
