# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xilinx/projects/example_project/example_project.srcs/sources_1/bd/zybo_example/ip/zybo_example_axi_interconnect_0_imp_auto_pc_0/zybo_example_axi_interconnect_0_imp_auto_pc_0.xci
# IP: The module: 'zybo_example_axi_interconnect_0_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx/projects/example_project/example_project.gen/sources_1/bd/zybo_example/ip/zybo_example_axi_interconnect_0_imp_auto_pc_0/zybo_example_axi_interconnect_0_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_example_axi_interconnect_0_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/xilinx/projects/example_project/example_project.srcs/sources_1/bd/zybo_example/ip/zybo_example_axi_interconnect_0_imp_auto_pc_0/zybo_example_axi_interconnect_0_imp_auto_pc_0.xci
# IP: The module: 'zybo_example_axi_interconnect_0_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx/projects/example_project/example_project.gen/sources_1/bd/zybo_example/ip/zybo_example_axi_interconnect_0_imp_auto_pc_0/zybo_example_axi_interconnect_0_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_example_axi_interconnect_0_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
