# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.runs/synth_1/.Xil/Vivado-26428-Ivan¡®sLaptop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z010clg400-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/b28c/hdl
    c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl
    c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/a4a8/hdl
    c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/434f/hdl
  } {
      D:/xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/xilinx/Vivado/2024.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      D:/xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/b28c/hdl
    c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl
    c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/a4a8/hdl
    c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/434f/hdl
  } {
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/synth/design_1.v
    }
      rt::read_verilog -include {
    c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/b28c/hdl
    c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl
    c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/a4a8/hdl
    c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/434f/hdl
  } {
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/2a7c/src/mmcme2_drp.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/synth/design_1_processing_system7_0_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/92b2/hdl/axi_register_slice_v2_1_vl_rfs.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/9692/hdl/axi_data_fifo_v2_1_vl_rfs.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/e9d8/hdl/axi_crossbar_v2_1_vl_rfs.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_xbar_2/synth/design_1_xbar_2.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/3c06/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/synth/design_1_auto_pc_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_xbar_3/synth/design_1_xbar_3.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_s00_regslice_0/synth/design_1_s00_regslice_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_s01_regslice_0/synth/design_1_s01_regslice_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_m00_regslice_0/synth/design_1_m00_regslice_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_auto_pc_1/synth/design_1_auto_pc_1.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/a4a8/hdl/axi_vdma_v6_3_rfs.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/ca8d/hdl/axis_register_slice_v1_1_vl_rfs.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_out_0/hdl/tdata_design_1_axis_subset_converter_out_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_out_0/hdl/tuser_design_1_axis_subset_converter_out_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_out_0/hdl/tstrb_design_1_axis_subset_converter_out_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_out_0/hdl/tkeep_design_1_axis_subset_converter_out_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_out_0/hdl/tid_design_1_axis_subset_converter_out_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_out_0/hdl/tdest_design_1_axis_subset_converter_out_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_out_0/hdl/tlast_design_1_axis_subset_converter_out_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/4bab/hdl/axis_subset_converter_v1_1_vl_rfs.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_out_0/hdl/top_design_1_axis_subset_converter_out_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_out_0/synth/design_1_axis_subset_converter_out_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_subset_converter_reset_0/synth/design_1_subset_converter_reset_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/52cd/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/synth/design_1_v_axi4s_vid_out_0_0.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/9fb1/hdl/integrator.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/9fb1/hdl/lorenz_solver.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/9fb1/hdl/signed_mult.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/9fb1/hdl/lorenz_dda_driver_slave_lite_v1_0_S00_AXI.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/9fb1/hdl/lorenz_dda_driver.v
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_lorenz_dda_driver_0_0/synth/design_1_lorenz_dda_driver_0_0.v
    }
      rt::read_vhdl -lib xpm D:/xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib xil_defaultlib {
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/2a7c/src/SyncAsync.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/2a7c/src/axi_dynclk_S00_AXI.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/2a7c/src/axi_dynclk.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_axi_dynclk_0_0/synth/design_1_axi_dynclk_0_0.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_fclk0_0/synth/design_1_proc_sys_reset_fclk0_0.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_fclk1_0/synth/design_1_proc_sys_reset_fclk1_0.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/d57c/src/ClockGen.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/d57c/src/SyncAsync.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/d57c/src/SyncAsyncReset.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/d57c/src/DVI_Constants.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/d57c/src/OutputSERDES.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/d57c/src/TMDS_Encoder.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/d57c/src/rgb2dvi.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_rgb2dvi_1_0/synth/design_1_rgb2dvi_1_0.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/synth/design_1_axi_vdma_0_0.vhd
      c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ip/design_1_v_tc_out_0/synth/design_1_v_tc_out_0.vhd
    }
      rt::read_vhdl -lib lib_cdc_v1_0_3 c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_15 c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/3a26/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_8 c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/09bd/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_10 c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/1443/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib lib_pkg_v1_0_4 c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_fifo_v1_0_19 c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/0a12/hdl/lib_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_bmg_v1_0_17 c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/3f29/hdl/lib_bmg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_4 c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_datamover_v5_1_33 c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/bf20/hdl/axi_datamover_v5_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_vdma_v6_3_19 c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/a4a8/hdl/axi_vdma_v6_3_rfs.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib v_tc_v6_2_8 c:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.gen/sources_1/bd/design_1/ipshared/5959/hdl/v_tc_v6_2_vh_rfs.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter lint_verbosity true
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/qijin/Documents/MEng_ZYBO/hdmi_driver/Zybo-Z7-HW/Zybo-Z7-HW.runs/synth_1/.Xil/Vivado-26428-Ivan¡®sLaptop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
